- name: Update
  apt:
    update_cache: yes
    upgrade: dist

- name: Install common packages
  apt:
    name:
      - curl
      - htop
      - apt-transport-https
      - software-properties-common
      - ca-certificates
      - git
      - gnupg
      - python3-pip
      - certbot
      - python3-certbot-nginx
    state: present
