- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start Nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Ensure Nginx is running
  systemd:
    name: nginx
    state: started
